# Generated by Django 5.0.4 on 2024-05-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pong2dGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.game')),
                ('ball_position_x', models.FloatField(default=0.0)),
                ('ball_position_y', models.FloatField(default=0.0)),
                ('ball_velocity_x', models.FloatField(default=1.0)),
                ('ball_velocity_y', models.FloatField(default=1.0)),
                ('player1_paddle_position', models.FloatField(default=0.0)),
                ('player2_paddle_position', models.FloatField(default=0.0)),
                ('game_over', models.BooleanField(default=False)),
            ],
            bases=('users.game',),
        ),
        migrations.CreateModel(
            name='Pong2dAIGame',
            fields=[
                ('pong2dgame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pong2d.pong2dgame')),
                ('ai_difficulty', models.CharField(default='medium', max_length=50)),
            ],
            bases=('pong2d.pong2dgame',),
        ),
    ]
