# Generated by Django 5.0.4 on 2024-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='game',
            field=models.CharField(default='pandapong_2d', max_length=50),
        ),
    ]
