# Generated by Django 5.0.4 on 2024-05-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_gameinvitation_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='game',
            field=models.CharField(max_length=50),
        ),
    ]
